<?php
/**
* Copyright © Rob Aimes - https://aimes.eu
*/

/**
 * @var $block \Aimes\ProductGallery\Block\Gallery
 */
?>
<div id="gallery-container" class="product-media" data-mage-init='{ "aimes/productGallery": { "initialImages": <?= $block->getJsImages() ?> } }' style="position: relative;">
    <div id="gallery-preview" class="gallery-preview">
        <?php foreach ($block->getProductImages() as $image): ?>
            <div><img data-lazy="<?= $image['img'] ?>" alt="<?= $image['caption'] ?>"/></div>
        <?php endforeach; ?>
    </div>
    <div id="gallery-nav" class="gallery-nav">
        <?php foreach ($block->getProductImages() as $image): ?>
            <div><img data-lazy="<?= $image['thumb'] ?>" alt="<?= $image['caption'] ?>"/></div>
        <?php endforeach; ?>
    </div>
</div>