<?php
/**
* Copyright © Rob Aimes - https://aimes.eu
*/

/**
 * @var $block \Aimes\ProductGallery\Block\Gallery
 */
?>
<div id="gallery-container" class="gallery-container product-media loading" data-bind="scope: 'product-gallery'">
    <div id="gallery-preview" class="gallery-preview" data-bind="foreach: { data: galleryImages, as: 'image' }, afterRender: initFlickity">
        <div class="gallery-cell" data-bind="css: { video: image.videoUrl }">
            <!-- ko if: image.videoUrl-->
            <iframe frameborder="0" data-bind="attr: { src: $parent.getVideoEmbedUrl(image.videoUrl), class: $parent.getService(image.videoUrl) }"></iframe>
            <!-- /ko -->

            <!-- ko ifnot: image.videoUrl -->
            <img data-bind="attr: { 'data-flickity-lazyload': image.full, alt: image.caption }"/>
            <!-- /ko -->
        </div>
    </div>
    <div id="gallery-nav" class="gallery-nav" data-bind="foreach: { data: galleryImages, as: 'image' }">
        <div class="gallery-cell" data-bind="css: { video: image.videoUrl }">
            <img data-bind="attr: { 'data-flickity-lazyload': image.thumb, alt: image.caption }"/>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
   {
       "*": {
           "Magento_Ui/js/core/app": {
               "components": {
                   "product-gallery": {
                       "component": "Aimes_ProductGallery/js/model/gallery",
                       "initialImages": <?= $block->getJsImages() ?>
                   }
               }
           }
       }
   }
</script>
<?php if($block->productHasVideo()): ?>
    <script type="text/x-magento-init">
    {
        "#gallery-container": {
            "aimes/product-gallery-video": {}
        }
    }
</script>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#gallery-container": {
            "aimes/product-gallery": {}
        }
    }
</script>
